[package]
name = "hello-world-guard-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies.risc0-zkvm]
version = "0.12.0"
git = "ssh://git@github.com/risc0/risc0.git"
default-features = false
